version: '2.2'
services:
  governify-nginx-streamer:
    container_name: governify-nginx-streamer
    image: nginx
    ports:
      - '443:443'
      - '80:80'
    ulimits:
      nproc: 10240
      nofile:
        soft: 10240
        hard: 10240
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    networks:
      - governify-bluejay
      - governify-galibo
      - governify-osseco
      - governify-falcon
      - governify-pompeia
      - governify-falcon
      - governify-pompeia
      - governify-services
      - lucidchain
    mem_limit: 100m
    restart: 'on-failure:5'
networks:
  governify-bluejay:
    external: true
  governify-galibo:
    external: true
  governify-osseco:
    external: true
  governify-falcon:
    external: true
  governify-pompeia:
    external: true
  lucidchain:
    external: true
  governify-services:
    external: true
