version: '2.2'
services:
  nginx-outside:
    container_name: nginx-gateway
    image: nginx
    ports:
      - '443:443'
      - '80:80'
    ulimits:
      nproc: 10240
      nofile:
        soft: 10240
        hard: 10240
    volumes:
      - './configurations/config/nginx.conf:/etc/nginx/nginx.conf'
      - './configurations/data/certbot/conf:/etc/letsencrypt'
      - './configurations/config/static:/etc/nginx/static'
      - './configurations/certs:/etc/nginx/certs'
      - './configurations/config/services-nginx-config:/etc/nginx/templates'
      - './configurations/data/certbot/www:/var/www/certbot'
    networks:
      - governify-bluejay
    mem_limit: 100m
    restart: 'on-failure:5'
networks:
  governify-bluejay:
    external: false
